### ISSUE TITLE
Script para montar un entorno enjaulado chroot

### ISSUE THREAD

**Issue by fryntiz** [fryntiz/ShellScript#11]
El script pedirá la partición que montar y donde montarla
- No se contempla más particiones (Solo 1 partición)
- Preguntará si montar o no partición
- Dará la opción para deshacer un entorno (Limpiar y salir)
- Encapsulado en funciones
- Portable para rehusarse con solo llamar a una función

Actualmente la creación de este script se lleva a cabo en la siguiente rama:
https://github.com/fryntiz/ShellScript/tree/11-Script-Chroot

**Comment by sergiotarxz** [comment]
https://github.com/fryntiz/ShellScript/pull/13

**Comment by fryntiz** [comment]
El desarrollo de este script está planteado aquí → https://github.com/fryntiz/ShellScript/blob/dr/Sistema/chroot.sh

**Comment by sergiotarxz** [comment]
Lo siento, no me di cuenta y además olvide añadir  el montaje para dev, sys y proc, trataré de ser más cuidadoso la próxima vez. (Pronto)

**Comment by fryntiz** [comment]
Tranquilo, sería interesante hacer una mezcla para terminarlo.
Tengo poco tiempo actualmente pero lo voy avanzando poco a poco. 
Puedes mirar lo que ya hay realizado y dar tu opinión o fusionar ambos scripts
